services:
    app:
        container_name: dicegame_app
        image: python:slim
        volumes:
            - ./:/app/
        working_dir: /app
        entrypoint: /app/entrypoint.sh
    nginx:
        image: nginx:latest
        container_name: dicegame_nginx
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./static/:/usr/share/nginx/html/static/
        ports:
            - "80:80"
        depends_on:
            - app
