# Generated by Django 4.2.3 on 2023-07-14 14:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.CharField(max_length=8, primary_key=True, serialize=False),
                ),
                (
                    "players",
                    models.ManyToManyField(
                        related_name="games", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
